### PR TITLE
Allow delegate target to come from macro expansion

### LINKED ISSUE #21: Delegate target cannot come from macro expansion
Take the following code:

```Rust
use delegate::delegate;

trait Trait{
  fn method_to_delegate(&self) -> bool;
}

struct Struct1();
impl Trait for Struct1 {
  fn method_to_delegate(&self) -> bool {
    true
  }
}

struct Struct2(pub Struct1);

// We use a macro to impl 'Trait' for 'Struct2' such that
// the target is a variable in the macro.
macro_rules! some_macro {
  ($delegate_to:expr) => {
    impl Trait for Struct2 {
      delegate!{
        // '$delegate' will expand to 'self.0' before ´delegate!' is expanded.
        to $delegate_to {
          fn method_to_delegate(&self) -> bool;
        }
      }
    }
  }
}
some_macro!{self.0}
```
This should work, as `$delegate_to` will expand to `self.0` and is therefore trivially correct. However, it currently fails to compile with the error:

```
error: proc macro panicked
  --> tests\in_macro_expansion.rs:25:4
   |
25 |               delegate!{
   |  _____________^
26 | |                 // '$delegate' will expand to 'self.0' before ´delegate!' is expanded.
27 | |                 to $delegate_to {
28 | |                     fn method_to_delegate(&self) -> bool;
29 | |                 }
30 | |             }
   | |_____________^
...
34 |   some_macro!{self.0}
   |   ------------------- in this macro invocation
   |
   = help: message: Use a field expression to select delegator (e.g. self.inner)

error: aborting due to previous error
```

The reason it fails is that macros expand variables into a group, which is a type of expression not handled by `delegate!`.

I'm working on a PR with a fix.

### PR DESCRIPTION
**Pull request by Emoun**
Fixes #21.

Please tell me if there are some changes you want made before merging.

### CODE REVIEW

**Comment by Kobzol** [comment]
Awesome! Thank you, it seems OK, so I'll merge it right away.

**Comment by Emoun** [comment]
Thanks for the quick response. Could I bother you to also make a new release, e.g. 0.4.1?
As far as I can tell, this should be a backwards compatible change.

**Comment by Kobzol** [comment]
Sure, I published a new version 0.4.1. I noticed that docs.rs can finally build this crate, so I will probably add some documentation to it and publish another (minor) version later.

**Comment by Emoun** [comment]
Great! Thanks again for fast response. v0.4.2 is working well for me.

**Pull request merged**
